version: "3.9"

services:
    webapp:
        build: ../dormafrica
        command: python manage.py runserver 0.0.0.0:8000
        container_name: django-cron
        volumes:
            - ../dormafrica:/usr/src/dormafrica
        env_file: ./.env
        ports:
            - 8000:8000
        depends_on:
            - db
    
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=dormafrica
            - POSTGRES_USER=myweb
            - POSTGRES_PASSWORD=Mountolympus1234

volumes:
    postgres_data: